markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "/it_styleguide"

version: 2.3.5

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/oneillray/it_styleguide
